name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls -la
          sudo apt-get install ncftp
          ncftpput -R -v -u "ftp_u@proprhome.com" -p "@Veera123" 92.205.2.171 _next _next/*
          sudo ftp -inv 92.205.2.171 <<EOF
          user ftp_u@proprhome.com @Veera123
          ls -la
          mput *
          bye
          EOF
      - run: echo "🍏 This job's status is ${{ job.status }}."
